- hosts: localhost 
  become: true 
  tasks: 
  - name: install zsh 
    apt: 
      name=zsh 
  - name: Change shell 
    shell: chsh -s `which zsh` 
  - name: install oh-my-zsh 
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: zsh autosuggestions
    ansible.builtin.git:
      repo: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
      dest: "~/.oh-my-zsh/custom" 
  - name: update our zshrc 
    shell: sed -i 's/(git(/git zsh-autosuggestions ~/.zshrc))'

  - name: Install node 
    apt: 
      name: ["nodejs", "npm"]

  - name: Install docker 
    
