- name: Install Visual Studio Code
  hosts: localhost
  become: yes  

  tasks:
    - name: Add VSCode repository GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
      when: ansible_os_family == "Ubuntu"
      tags:
        - vscode

    - name: Add VSCode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
      when: ansible_os_family == "Ubuntu"
      tags:
        - vscode

    - name: Install Visual Studio Code
      package:
        name: code
        state: present
      tags:
        - vscode

