- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags:
    - docker

- name: Add user to the docker group
  user:
    name: badal
    groups: docker
    append: yes
  tags:
    - docker
